-- 회사 Oracle 용 — schema_sqlite.sql 과 같은 구조.
-- user_store.py 의 SQL 은 :name 바인딩이라 그대로 쓰되, 아래 두 군데는 Oracle 문법으로 바꿔야 한다:
--   1) INSERT ... ON CONFLICT DO UPDATE  →  MERGE INTO ... USING dual ...
--   2) LIMIT :limit                       →  FETCH FIRST :limit ROWS ONLY
CREATE TABLE users (
  user_id      VARCHAR2(64) PRIMARY KEY,
  name         VARCHAR2(200) NOT NULL,
  dept         VARCHAR2(200) DEFAULT '',
  email        VARCHAR2(200) DEFAULT '',
  profile_json CLOB DEFAULT '{}',
  created_at   VARCHAR2(19) NOT NULL,
  last_seen    VARCHAR2(19) NOT NULL
);

CREATE TABLE user_memory (
  user_id    VARCHAR2(64) PRIMARY KEY REFERENCES users(user_id),
  content    CLOB NOT NULL,
  version    NUMBER(10) NOT NULL,
  updated_at VARCHAR2(19) NOT NULL,
  source     VARCHAR2(20) NOT NULL
);

CREATE TABLE user_memory_history (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    VARCHAR2(64) NOT NULL,
  version    NUMBER(10) NOT NULL,
  content    CLOB NOT NULL,
  source     VARCHAR2(20) NOT NULL,
  created_at VARCHAR2(19) NOT NULL
);
CREATE INDEX ix_umh_user ON user_memory_history (user_id, version);
